apiVersion: v1
kind: Service
metadata:
  name: apigw-service
  namespace: configuration-server
spec:
  selector:
    app: apigw-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30084
  type: NodePort
