apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-ns
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30045
  type: NodePort
