apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: configuration-server
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30042
  type: NodePort
