apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: postgres-ns
spec:
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30089
  type: NodePort
