apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: configuration-server
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 30083
  type: NodePort
