apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: configuration-server
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30082
  type: NodePort
